---
stages:
  - test
  - cleanup
  - deploy

test_api:
  stage: test
  script:
    - make single-test TEST_NAME=api
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_api_migration:
  stage: test
  script:
    - make single-test TEST_NAME=api-migration
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_js:
  stage: test
  script:
    - make single-test TEST_NAME=js
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_python:
  stage: test
  script:
    - make single-test TEST_NAME=common
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_e2e:
  stage: test
  script:
    - make e2e-test
  only:
    - dev

cleanup_e2e:
  stage: cleanup
  script:
    - make cleanup-e2e BRANCH=test
  when: on_failure

build_core:
  stage: deploy
  script:
    - make core push
  only:
    - build-dev

bot_build:
  stage: deploy
  script:
    - if [ -n "${DEV_CHANNEL}" ]; then make release; docker stop ella; docker rm ella; docker run -d --name demo.allel.es -e VIRTUAL_HOST=demo.allel.es --expose 80 ousamg/ella.release; docker exec demo.allel.es make dbreset; fi
    - if [ -n "${BETA_CHANNEL}" ]; then make release BUILD_TYPE=beta; docker stop ella; docker rm ella; docker run -d --name beta.allel.es -e VIRTUAL_HOST=beta.allel.es --expose 80 ousamg/ella.beta; docker exec beta.allel.es make dbreset; fi
  tags:
    - web
  only:
    - triggers
