---
run_genap_tests:
  script:
    - make test BRANCH=test

run_genap_e2e_tests:
  script:
    - make test-e2e-main API_HOST='localhost' API_PORT=9999 SELENIUM_ADDRESS=http://172.16.250.128:4444/wd/hub BRANCH=test
  only:
    - 533-e2e