---
stages:
  - test
  - cleanup
  - deploy
  - review
  - notify

test_api:
  stage: test
  script:
    - make single-test TEST_NAME=api
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_api_migration:
  stage: test
  script:
    - make single-test TEST_NAME=api-migration
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_js:
  stage: test
  script:
    - make single-test TEST_NAME=js
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  allow_failure: true

test_python:
  stage: test
  script:
    - make single-test TEST_NAME=common
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_e2e:
  stage: test
  script:
    - make e2e-test
  except:
    - /^ui-.*$/
    - /^ops-.*$/

build_core:
  stage: deploy
  script:
    - if [ -n "${BUILD_CORE}" ]; then make core push; fi
  only:
    - triggers

bot_build:
  stage: deploy
  script:
    - if [ -n "${DEV_CHANNEL}" ]; then make release deploy DEPLOY_NAME=demo.allel.es; fi
    - if [ -n "${BETA_CHANNEL}" ]; then make release deploy BUILD_TYPE=beta DEPLOY_NAME=beta.allel.es; fi
    - if [ -n "${REVIEW_CHANNEL}" ]; then make release deploy BUILD_TYPE=${REVIEW_CHANNEL} DEPLOY_NAME=${REVIEW_CHANNEL}.review.ousamg.io; fi
  tags:
    - web
  only:
    - triggers

bot_notify_failure:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/failure'
  when: on_failure
  only:
    - triggers
    - branches

bot_notify_success:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/success'
  when: on_success
  only:
    - triggers
    - branches

start_review:
  stage: review
  script:
    - make release deploy BUILD_TYPE=${CI_BUILD_REF_SLUG} DEPLOY_NAME=${CI_BUILD_REF_SLUG}.review.ousamg.io
  environment:
    name: review/$CI_BUILD_REF_SLUG
    url: http://$CI_BUILD_REF_SLUG.review.$APPS_DOMAIN
    on_stop: stop_review
  when: always
  only:
    - branches
  except:
    - master
  tags:
    - web

# when: manual is also run upon branch deletion
stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - docker rm -f ${CI_BUILD_REF_SLUG}.review.ousamg.io; docker rmi -f ousamg/ella.${CI_BUILD_REF_SLUG};
  when: manual
  environment:
    name: review/$CI_BUILD_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - web



