---
stages:
  - test
  - cleanup
  - deploy
  - notify

test_api:
  stage: test
  script:
    - make single-test TEST_NAME=api
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_api_migration:
  stage: test
  script:
    - make single-test TEST_NAME=api-migration
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_js:
  stage: test
  script:
    - make single-test TEST_NAME=js
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  allow_failure: true

test_python:
  stage: test
  script:
    - make single-test TEST_NAME=common
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_e2e:
  stage: test
  script:
    - make e2e-test
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  allow_failure: true

cleanup_e2e:
  stage: cleanup
  script:
    - make cleanup-e2e BRANCH=test
  when: on_failure

build_core:
  stage: deploy
  script:
    - if [ -n "${BUILD_CORE}" ]; then make core push; fi
  only:
    - triggers

bot_build:
  stage: deploy
  script:
    - if [ -n "${DEV_CHANNEL}" ]; then make release deploy DEPLOY_NAME=demo.allel.es,demo.ella.ousamg.io; fi
    - if [ -n "${BETA_CHANNEL}" ]; then make release deploy BUILD_TYPE=beta DEPLOY_NAME=beta.allel.es,beta.ella.ousamg.io; fi
  tags:
    - web
  only:
    - triggers

bot_notify_failure:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/failure'
  when: on_failure
  only:
    - triggers

bot_notify_success:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/success'
  when: on_success
  only:
    - triggers
