---
stages:
  - release

release:
  stage: release
  script:
    - RELEASE_TAG=${CI_COMMIT_TAG} make bundle-api
    - RELEASE_TAG=${CI_COMMIT_TAG} make bundle-static
  artifacts:
    paths:
    - ella-${CI_COMMIT_TAG}-web.tgz
    - ella-${CI_COMMIT_TAG}-api.tgz
    name: ${CI_COMMIT_TAG}
  when: always
  only:
    - tags


