---
variables:
  BRANCH: $CI_COMMIT_REF_NAME
  PIPELINE_ID: ella-$CI_PIPELINE_ID

stages:
  - test
  - e2e-setup
  - e2e
  - reports
  - deploy
  - review
  - notify
  - release
  - cleanup


test_api:
  stage: test
  script:
    - make test-api
  except:
    - /^ui-.*$/
    - /^ops-.*$/


test_api_migration:
  stage: test
  script:
    - make test-api-migration
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  allow_failure: true


test_js:
  stage: test
  script:
    - make test-js
  except:
    - /^ui-.*$/
    - /^ops-.*$/


test_python:
  stage: test
  script:
    - make test-common
  except:
    - /^ui-.*$/
    - /^ops-.*$/


test_rule_engine:
  stage: test
  script:
    - make test-rule-engine
  except:
    - /^ui-.*$/
    - /^ops-.*$/


test_cli:
  stage: test
  script:
    - make test-cli


e2e-container-startup:
  stage: e2e-setup
  script:
    - make e2e-app-container-setup
  except:
    - /^ui-.*$/
    - /^ops-.*$/


test_e2e:
  stage: e2e
  script:
    - make test-e2e
  before_script:
    - rm -rf errorShots
  after_script:
    - docker exec ${PIPELINE_ID}-e2e tar c -C /ella/errorShots/ -f - . > errorShots.tar && mkdir errorShots && tar x -C errorShots -f errorShots.tar
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  artifacts:
      paths:
      - errorShots/*.png
      name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
      when: on_failure
      expire_in: 1 week



test_reports:
  stage: reports
  script:
    - make test-report-sanger
    - make test-report-classifications
  before_script:
    - rm -rf errorShots
  after_script:
    - docker exec ${PIPELINE_ID}-e2e tar c -C /ella/errorShots/ -f - . > errorShots.tar && mkdir errorShots && tar x -C errorShots -f errorShots.tar
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  artifacts:
      paths:
      - errorShots/*.png
      name: ella-report-errors-${CI_BUILD_REF_SLUG}
      when: on_failure
      expire_in: 1 week


cleanup:
  stage: cleanup
  script:
    - docker ps -aq --filter "name=${PIPELINE_ID}-*" | xargs -r docker rm  -f -v
    - docker images --quiet --filter "reference=local/${PIPELINE_ID}*" | xargs -r docker rmi
  when: always


bot_build:
  stage: deploy
  script:
    - if [ -n "${DEV_CHANNEL}" ]; then make demo DEMO_NAME=demo.allel.es; fi
    - if [ -n "${BETA_CHANNEL}" ]; then make demo DEMO_NAME=beta.allel.es; fi
  tags:
    - web
  only:
    - triggers


bot_notify_failure:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/failure'
  when: on_failure
  only:
    - triggers
    - branches


bot_notify_success:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/success'
  when: on_success
  only:
    - triggers
    - branches


start_review:
  stage: review
  script:
    - make demo DEMO_NAME=${CI_BUILD_REF_SLUG}.review.ousamg.io
  environment:
    name: review/$CI_BUILD_REF_SLUG
    url: http://$CI_BUILD_REF_SLUG.review.$APPS_DOMAIN
    on_stop: stop_review
  when: always
  only:
    - branches
  except:
    - master
  tags:
    - web


# when: manual is also run upon branch deletion
# Image name for removal (local/${CI_BUILD_REF_NAME}.review.ousamg.io) is from Makefile
stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - docker rm -f ${CI_BUILD_REF_SLUG}.review.ousamg.io; docker rmi -f local/${CI_BUILD_REF_SLUG}.review.ousamg.io;
  when: manual
  environment:
    name: review/$CI_BUILD_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - web


release:
  stage: release
  script:
    - RELEASE_TAG=$CI_COMMIT_REF_NAME make bundle-dist
    - make release-notes
  artifacts:
    paths:
    - ella-release-$CI_COMMIT_REF_NAME-*.tgz
    - ella-releasenotes*.txt
    name: ella-release-$CI_COMMIT_REF_NAME
    when: on_success
    expire_in: 1 mo
  when: on_success
  only:
    - tags
