---
variables:
  BRANCH: $CI_COMMIT_REF_NAME
  PIPELINE_ID: ella-$CI_PIPELINE_ID

stages:
  - test
  - e2e
  - deploy
  - review
  - release


test_api:
  stage: test
  script:
    - make test-api
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  after_script:
    - docker rm  -f -v ${PIPELINE_ID}-api


test_api_migration:
  stage: test
  script:
    - make test-api-migration
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  after_script:
    - docker rm  -f -v ${PIPELINE_ID}-api-migration


test_js:
  stage: test
  script:
    - make test-js
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  after_script:
    - docker rm  -f -v ${PIPELINE_ID}-js


test_python:
  stage: test
  script:
    - make test-common
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  after_script:
    - docker rm  -f -v ${PIPELINE_ID}-common


test_cli:
  stage: test
  script:
    - make test-cli
  after_script:
    - docker rm  -f -v ${PIPELINE_ID}-cli


test_e2e:
  stage: e2e
  script:
    - make test-e2e
  before_script:
    - rm -rf errorShots
  after_script:
    - docker exec ${PIPELINE_ID}-e2e tar c -C /ella/errorShots/ -f - . > errorShots.tar && mkdir errorShots && tar x -C errorShots -f errorShots.tar
    - docker rm  -f -v ${PIPELINE_ID}-e2e
    - docker rm  -f -v ${PIPELINE_ID}-chromebox
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  artifacts:
      paths:
      - errorShots/*.png
      name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
      when: on_failure
      expire_in: 2 weeks


start_review:
  stage: review
  script:
    - make demo DEMO_NAME=${CI_BUILD_REF_SLUG}.review.ousamg.io
  environment:
    name: review/$CI_BUILD_REF_SLUG
    url: http://$CI_BUILD_REF_SLUG.review.$APPS_DOMAIN
    on_stop: stop_review
  when: always
  only:
    - branches
  except:
    - master
  tags:
    - web


# when: manual is also run upon branch deletion
# Image name for removal (local/ella-${CI_BUILD_REF_NAME}.review.ousamg.io) is from Makefile
stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - docker rm -f ella-${CI_BUILD_REF_SLUG}.review.ousamg.io; docker rmi -f local/ella-${CI_BUILD_REF_SLUG}.review.ousamg.io;
  when: manual
  environment:
    name: review/$CI_BUILD_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - web


release:
  stage: release
  script:
    - RELEASE_TAG=$CI_COMMIT_REF_NAME make bundle-dist
    - make release-notes
  artifacts:
    paths:
    - ella-release-$CI_COMMIT_REF_NAME-*.tgz
    - ella-releasenotes*.txt
    name: ella-release-$CI_COMMIT_REF_NAME
    when: on_success
    expire_in: 1 mo
  when: on_success
  only:
    - tags
