---
variables:
  BRANCH: $CI_COMMIT_REF_NAME

stages:
  - test
  - e2e
  - deploy
  - review
  - notify
  - release
  - cleanup

test_api:
  stage: test
  script:
    - make single-test TEST_NAME=api
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_api_migration:
  stage: test
  script:
    - make single-test TEST_NAME=api-migration
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  allow_failure: true

test_js:
  stage: test
  script:
    - make single-test TEST_NAME=js
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_python:
  stage: test
  script:
    - make single-test TEST_NAME=common
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_rule_engine:
  stage: test
  script:
    - make single-test TEST_NAME=rule-engine
  except:
    - /^ui-.*$/
    - /^ops-.*$/


test_e2e:
  stage: e2e
  script:
    - make e2e-test
  except:
    - /^ui-.*$/
    - /^ops-.*$/
  artifacts:
      paths:
      - errorShots/*.png
      name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
      when: on_failure

cleanup_e2e:
  stage: cleanup
  script:
    - make e2e-stop-chromebox
  when: always

bot_build:
  stage: deploy
  script:
    - if [ -n "${DEV_CHANNEL}" ]; then make demo DEMO_NAME=demo.allel.es; fi
    - if [ -n "${BETA_CHANNEL}" ]; then make demo DEMO_NAME=beta.allel.es; fi
  tags:
    - web
  only:
    - triggers

bot_notify_failure:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/failure'
  when: on_failure
  only:
    - triggers
    - branches

bot_notify_success:
  stage: notify
  script:
    - curl '127.0.0.1:8080/notify/success'
  when: on_success
  only:
    - triggers
    - branches

start_review:
  stage: review
  script:
    - make demo DEMO_NAME=${CI_BUILD_REF_SLUG}.review.ousamg.io
  environment:
    name: review/$CI_BUILD_REF_SLUG
    url: http://$CI_BUILD_REF_SLUG.review.$APPS_DOMAIN
    on_stop: stop_review
  when: always
  only:
    - branches
  except:
    - master
  tags:
    - web

# when: manual is also run upon branch deletion
# Image name for removal (local/${CI_BUILD_REF_NAME}.review.ousamg.io) is from Makefile
stop_review:
  stage: review
  variables:
    GIT_STRATEGY: none
  script:
    - docker rm -f ${CI_BUILD_REF_SLUG}.review.ousamg.io; docker rmi -f local/${CI_BUILD_REF_SLUG}.review.ousamg.io;
  when: manual
  environment:
    name: review/$CI_BUILD_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - master
  tags:
    - web


release:
  stage: release
  script:
    - RELEASE_TAG=$CI_COMMIT_REF_NAME make bundle-dist
  artifacts:
    paths:
    - ella-release-$CI_COMMIT_REF_NAME-*.tgz
    name: ella-release-$CI_COMMIT_REF_NAME
    when: on_success
  when: on_success
  only:
    - tags
