---
image: docker:latest
services:
    - docker:dind

variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CI_CACHE_IMAGE_FILE: ella-ci-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID.tar
    DOCKER_DRIVER: overlay2
    BRANCH: $CI_COMMIT_REF_NAME
    PIPELINE_ID: ella-$CI_PIPELINE_ID

stages:
    - build
    - formatting
    - test
    - e2e
    - review
    - release

build:
    stage: build
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:ci-latest || true
        - docker build --cache-from $CI_REGISTRY_IMAGE:ci-latest -t $CI_REGISTRY_IMAGE:ci-latest -t $IMAGE_NAME -t ella:ci-latest --target production-build .
        - docker push $CI_REGISTRY_IMAGE:ci-latest
        - mkdir -p images
        - docker save $IMAGE_NAME > images/$CI_CACHE_IMAGE_FILE
    tags:
        - do-small
    cache:
        key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
        paths:
            - images/
        policy: push

start_review:
    stage: review
    script:
        - make review REVIEW_NAME=${CI_BUILD_REF_SLUG}.review.ousamg.io
    environment:
        name: review/$CI_BUILD_REF_SLUG
        url: http://$CI_BUILD_REF_SLUG.review.ousamg.io
    only:
        - branches
    except:
        - master
    tags:
        - review
    needs: []

.test-common:
    stage: test
    before_script:
        - apk add --update make
        - cat images/$CI_CACHE_IMAGE_FILE | docker load
    needs: ['build']
    tags:
        - do-small
    cache:
        key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
        paths:
            - images/
        policy: pull

check_formatting:
    extends: .test-common
    stage: formatting
    script:
        - make test-formatting
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-formatting
    tags:
        - do-small

api:
    extends: .test-common
    script:
        - make test-api
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-api
    tags:
        - do-small

api_migration:
    extends: .test-common
    script:
        - make test-api-migration
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-api-migration
    tags:
        - do-small

js:
    extends: .test-common
    script:
        - make test-js
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-js
    tags:
        - do-small

python:
    extends: .test-common
    script:
        - make test-python
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-common
    tags:
        - do-small

cli:
    extends: .test-common
    script:
        - make test-cli
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-cli
    tags:
        - do-small

report:
    extends: .test-common
    script:
        - make test-report
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-report
    tags:
        - do-small

.test_e2e:
    stage: e2e
    before_script:
        - apk add --update make
        - cat images/$CI_CACHE_IMAGE_FILE | docker load
        - rm -rf errorShots
    after_script:
        - docker rm  -f -v ${PIPELINE_ID}-e2e
    except:
        - /^ui-.*$/
        - /^ops-.*$/
    artifacts:
        paths:
            - errorShots/*.png
        name: ella-e2e-errors-${CI_BUILD_REF_SLUG}
        when: on_failure
        expire_in: 2 weeks
    variables:
        BUILD: 'false'
    needs: ['build']
    tags:
        - do-small
    cache:
        key: 'ella-$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
        paths:
            - images/
        policy: pull

ci_all_e2e_tests:
    extends: .test-common
    stage: e2e
    script:
        - make test-check-ci-e2e-tests

import_analysis:
    extends: .test_e2e
    script: SPEC=import_analysis.js make test-e2e

search_allele_and_analyses:
    extends: .test_e2e
    script: SPEC=search_alleles_and_analyses.js make test-e2e

workflow_sample_classification:
    extends: .test_e2e
    script: SPEC=workflow_sample_classification.js make test-e2e

workflow_sample_collisions:
    extends: .test_e2e
    script: SPEC=workflow_sample_collisions.js make test-e2e

workflow_sample_interpretation_rounds:
    extends: .test_e2e
    script: SPEC=workflow_sample_interpretation_rounds.js make test-e2e

workflow_variant_acmg:
    extends: .test_e2e
    script: SPEC=workflow_variant_acmg.js make test-e2e

workflow_variant_classification:
    extends: .test_e2e
    script: SPEC=workflow_variant_classification.js make test-e2e

workflow_variant_readonly:
    extends: .test_e2e
    script: SPEC=workflow_variant_readonly.js make test-e2e

workflow_variant_references:
    extends: .test_e2e
    script: SPEC=workflow_variant_references.js make test-e2e

workflow_not_saved_warnings:
    extends: .test_e2e
    script: SPEC=workflow_not_saved_warnings.js make test-e2e

release:
    stage: release
    before_script:
        - apk add --update make git
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $IMAGE_NAME | cat
    script:
        - RELEASE_TAG=$CI_COMMIT_REF_NAME make bundle-dist
        - ops/gitlab_create_release.sh $CI_JOB_TOKEN $CI_COMMIT_REF_NAME
    artifacts:
        paths:
            - ella-release-$CI_COMMIT_REF_NAME-*.tgz
        name: ella-release-$CI_COMMIT_REF_NAME
        when: on_success
        expire_in: 1 mo
    when: on_success
    only:
        - tags
    tags:
        - do-small
