---
test_api:
  script:
    - make single-test TEST_NAME=api
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_js:
  script:
    - make single-test TEST_NAME=js
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_python:
  script:
    - make single-test TEST_NAME=common
  except:
    - /^ui-.*$/
    - /^ops-.*$/

test_e2e:
  script:
    - make e2e-test
  except:
    - /^ui-.*$/
    - /^ops-.*$/

build_dev_image:
  script:
    - make dev-release
  only:
    - build-dev
