app:
  links_to_clipboard: !env_bool [OFFLINE_MODE, true]
  non_production_warning: !env_str NON_PRODUCTION_WARNING
  annotation_service: !env [ANNOTATION_SERVICE_URL, "http://localhost:6000"]
  attachment_storage: !env "ATTACHMENT_STORAGE"
  max_upload_size: 52428800 # 50 MB
user:
  # Password policy
  auth:
    # Number of days a password is valid before it needs changing.
    # All sessions will be invalidated when the password is expired.
    # Note: Changing this will not affect existing passwords
    password_expiry_days: 90
    # Min length of password
    password_minimum_length: 8
    # Password strength requirements
    password_match_groups_descr:
      - Uppercase letters [A-Z]
      - Lowercase letters [a-z]
      - Digits [0-9]
      - Special characters
    password_match_groups:
      - ".*[A-Z].*"
      - ".*[a-z].*"
      - ".*[0-9].*"
      - ".*[^A-Za-z0-9].*"
    # Number of the match groups that must be satisfied
    password_num_match_groups: 3
  user_config:
    # Default user config
    # Is _shallow_ merged with usergroup's and user's config at runtime
    overview:
      # Available: analyses, analyses-by-findings, variants, import
      views:
        - analyses
        - import
    workflows:
      allele:
        finalize_requirements:
          # Workflow statuses allowing finalization of variants
          workflow_status:
            - Interpretation
            - Review
      analysis:
        finalize_requirements:
          # Workflow statuses allowing finalization of analyses
          workflow_status:
            - Not ready
            - Interpretation
            - Review
            - Medical review
          # Allow not relevant/technical variants without classification when finalizing analysis
          allow_notrelevant: false
          allow_technical: true
          # allow_unclassified implies allow_technical and allow_notrelevant
          allow_unclassified: false
    acmg:
      frequency:
        thresholds:
          AD:
            external:
              hi_freq_cutoff: 0.005
              lo_freq_cutoff: 0.001
            internal:
              hi_freq_cutoff: 0.05
              lo_freq_cutoff: 1
          default:
            external:
              hi_freq_cutoff: 0.01
              lo_freq_cutoff: 1
            internal:
              hi_freq_cutoff: 0.05
              lo_freq_cutoff: 1
        num_thresholds:
          GNOMAD_GENOMES:
            G: 5000
            AFR: 5000
            AMR: 5000
            EAS: 5000
            FIN: 5000
            NFE: 5000
            OTH: 5000
            SAS: 5000
          GNOMAD_EXOMES:
            G: 5000
            AFR: 5000
            AMR: 5000
            EAS: 5000
            FIN: 5000
            NFE: 5000
            OTH: 5000
            SAS: 5000
      disease_mode: ANY
      last_exon_important: LEI
    interpretation:
      autoIgnoreReferencePubmedIds: []
analysis:
  priority:
    # Display text for priority 1,2,3
    display:
      "1": Normal
      "2": High
      "3": Urgent
  sidebar:
    # Sidebar configuration for the different sidebar views
    full:
      columns: []
      classification_options:
        unclassified: []
        classified: []
        not_relevant: []
        technical: []
      comment_type:
        unclassified:
        classified:
        not_relevant:
        technical:
      shade_multiple_in_gene: true
    quick:
      columns:
        - qual
        - dp
        - ratio
        - hi-freq
        - hi-count
        - external
      classification_options:
        unclassified:
          - technical
          - notrelevant
          - classu
          - class2
        classified: []
        not_relevant: []
        technical: []
      comment_type:
        unclassified:
        classified: evaluation
        not_relevant: analysis
        technical: analysis
      narrow_comment: false
      shade_multiple_in_gene: true
    visual:
      columns:
        - qual
        - ratio
      classification_options:
        unclassified:
          - technical
        classified:
          - technical
        not_relevant: []
        technical: []
      comment_type:
        unclassified:
        classified:
        not_relevant: analysis
        technical: analysis
      narrow_comment: true
      shade_multiple_in_gene: true
    report:
      columns: []
      classification_options:
        unclassified: []
        classified: []
        not_relevant: []
        technical: []
      comment_type:
        unclassified:
        classified:
        not_relevant:
        technical:
      shade_multiple_in_gene: true
    list:
      columns:
        - qual
        - dp
        - ratio
        - hi-freq
        - hi-count
        - external
      classification_options:
        unclassified: []
        classified: []
        not_relevant: []
        technical: []
      comment_options:
        unclassified:
        classified:
        not_relevant:
        technical:
      shade_multiple_in_gene: false
annotation:
  clinvar:
    clinical_significance_status:
      criteria provided, conflicting interpretations: 1
      criteria provided, multiple submitters, no conflicts: 2
      criteria provided, single submitter: 1
      no assertion criteria provided: 0
      no assertion provided: 0
      practice guideline: 4
      reviewed by expert panel: 3
frequencies:
  groups:
    external:
      GNOMAD_GENOMES:
        - G
        - AFR
        - AMR
        - EAS
        - NFE
        - OTH
        - SAS
      GNOMAD_EXOMES:
        - G
        - AFR
        - AMR
        - EAS
        - NFE
        - OTH
        - SAS
    internal:
      inDB:
        - OUSWES
  view:
    groups:
      GNOMAD_GENOMES:
        - G
        - AFR
        - AMR
        - ASJ
        - EAS
        - FIN
        - NFE
        - OTH
        - SAS
      GNOMAD_EXOMES:
        - G
        - AFR
        - AMR
        - ASJ
        - EAS
        - FIN
        - NFE
        - OTH
        - SAS
      ExAC:
        - G
        - AFR
        - AMR
        - EAS
        - FIN
        - NFE
        - OTH
        - SAS
      1000g:
        - G
        - AMR
        - ASN
        - EUR
        - EAS
        - SAS
      esp6500:
        - AA
        - EA
      inDB:
        - OUSWES
    precision: 6
    scientific_threshold: 4
    indications_threshold: 10
    GNOMAD_GENOMES:
      G: TOT
      AFR: AFR
      AMR: LAT
      ASJ: ASJ
      EAS: EA
      FIN: E(F)
      NFE: E(NF)
      OTH: OTH
      SAS: SA
    GNOMAD_EXOMES:
      G: TOT
      AFR: AFR
      AMR: LAT
      ASJ: ASJ
      EAS: EA
      FIN: E(F)
      NFE: E(NF)
      OTH: OTH
      SAS: SA
    ExAC:
      G: TOT
      AFR: AFR
      AMR: LAT
      EAS: EA
      FIN: E(F)
      NFE: E(NF)
      OTH: OTH
      SAS: SA
filter:
  default_filter_config:
    region:
      splice_region:
        - -20
        - 6
      utr_region:
        - 0
        - 0
    frequency:
      num_thresholds:
        GNOMAD_GENOMES:
          G: 5000
          AFR: 5000
          AMR: 5000
          EAS: 5000
          NFE: 5000
          OTH: 5000
          SAS: 5000
        GNOMAD_EXOMES:
          G: 5000
          AFR: 5000
          AMR: 5000
          EAS: 5000
          NFE: 5000
          OTH: 5000
          SAS: 5000
      thresholds:
        AD:
          external: 0.005
          internal: 0.05
        default:
          external: 0.01
          internal: 0.05
    inheritancemodel: {}
    quality: {}
    segregation: {}
    external: {}
    classification: {}
    ppy: {}
    consequence: {}
classification:
  gene_groups:
    MMR:
      - MLH1
      - MSH2
      - MSH6
      - PMS2
  options:
    - name: Class U
      value: U
    - name: Class 1
      value: "1"
    - name: Class 2
      value: "2"
      outdated_after_days: 365
    - name: Class 3
      value: "3"
      outdated_after_days: 180
      include_report: true
      include_analysis_with_findings: true
    - name: Class 4
      value: "4"
      outdated_after_days: 180
      include_report: true
      include_analysis_with_findings: true
    - name: Class 5
      value: "5"
      outdated_after_days: 365
      include_report: true
      include_analysis_with_findings: true
    - name: Drug response
      value: DR
report:
  classification_text:
    "1": Ikke sykdomsgivende variant
    "2": Sannsynlig ikke sykdomsgivende variant
    "3": Variant med usikker betydning
    "4": Sannsynlig sykdomsgivende variant
    "5": Sykdomsgivende variant
transcripts:
  consequences:
    - transcript_ablation
    - splice_donor_variant
    - splice_acceptor_variant
    - stop_gained
    - frameshift_variant
    - start_lost
    - initiator_codon_variant
    - stop_lost
    - inframe_insertion
    - inframe_deletion
    - missense_variant
    - protein_altering_variant
    - transcript_amplification
    - splice_region_variant
    - incomplete_terminal_codon_variant
    - synonymous_variant
    - stop_retained_variant
    - coding_sequence_variant
    - mature_miRNA_variant
    - 5_prime_UTR_variant
    - 3_prime_UTR_variant
    - non_coding_transcript_exon_variant
    - non_coding_transcript_variant
    - intron_variant
    - NMD_transcript_variant
    - upstream_gene_variant
    - downstream_gene_variant
    - TFBS_ablation
    - TFBS_amplification
    - TF_binding_site_variant
    - regulatory_region_variant
    - regulatory_region_ablation
    - regulatory_region_amplification
    - feature_elongation
    - feature_truncation
    - intergenic_variant
  inclusion_regex: NM_.*
igv:
  reference:
    fastaURL: api/v1/igv/human_g1k_v37_decoy.fasta
    cytobandURL: api/v1/igv/cytoBand.txt
  valid_resource_files:
    - cytoBand.txt
    - human_g1k_v37_decoy.fasta
    - human_g1k_v37_decoy.fasta.fai
import:
  automatic_deposit_with_sample_id: false
  preimport_script: !file "scripts/preimport.py" # Relative to ELLA root folder
